### ISSUE TITLE
Two Broken Links on Making ReadME Page

### ISSUE THREAD

**Issue by jfc3-dol** [18F/open-source-guide#28]
There are two broken links on this page ( https://pages.18f.gov/open-source-guide/making-readmes-readable/ ).

The links are "developing the site" - ( https://github.com/18F/18f.gsa.gov#developing-the-site ) and "deploying the site" - ( https://github.com/18F/18f.gsa.gov#deploying-the-site ).

Not sure why the "18f.gsa.gov" is in the middle of the link and not proper ReadMe.

**Comment by jfc3-dol** [comment]
Actually, I found and other broken link for the "installation instructions" - https://github.com/openopps/openopps-platform/blob/devel/INSTALL.md

**Comment by gbinal** [comment]
#29 should address these.  

P.S.  

> Not sure why the "18f.gsa.gov" is in the middle of the link and not proper ReadMe.

It's just the nature of the repo name and how the anchor links in the readme work.

**Comment by jfc3-dol** [comment]
Thanks, glad you are going to attempt to correct the issue.
