### ISSUE TITLE
merge (or link between) related resources

### ISSUE THREAD

**Issue by afeld** [18F/open-source-guide#4]
We have some other related resources:
- https://pages.18f.gov/before-you-ship/
- https://pages.18f.gov/open-source-program/pages/maintainer_guidelines/
- https://github.com/18F/open-source-policy/blob/master/practice.md

@melodykramer Did you go through each of these already to consider what content should be where, or is it worth another pass?

**Comment by melodykramer** [comment]
I did, linked to the third document, and integrated much of what's in the second document into the guide. I can add the link to the open source guide to each of these.

**Comment by afeld** [comment]
Awesome, thanks!
- [x] Link from https://pages.18f.gov/before-you-ship/
- [ ] :bomb: https://pages.18f.gov/open-source-program/pages/maintainer_guidelines/
- [x] Link from https://pages.18f.gov/open-source-program/

**Comment by melodykramer** [comment]
I added information to all three, @afeld.
