### ISSUE TITLE
give attribution to CFPB for the theme

### ISSUE THREAD

**Issue by jpyuda** [18F/open-source-guide#5]
We've been using DOCter for these types of pages a lot (which is good!). But we don't send any kind of link or attribution back to https://github.com/cfpb/docter. We should.

**Comment by mbland** [comment]
We did give the hat tip in
- The Guides annoucement: https://18f.gsa.gov/2015/05/28/18F-guides/
- The Guides Template repo README: https://github.com/18F/guides-template

but we could probably put it more places. We can add it to 18F/guides-template, and use that to update the Guides accordingly.

**Comment by jpyuda** [comment]
I missed that. Awesome!

**Comment by mbland** [comment]
Forgot to mention, it's also mentioned in the very first line of [the published Guides Template](https://pages.18f.gov/guides-template/), FWIW.

**Comment by melodykramer** [comment]
Adding to README.

**Comment by melodykramer** [comment]
https://github.com/18F/open-source-guide/pull/9 Done!
