### ISSUE TITLE
Suggestions for naming?

### ISSUE THREAD

**Issue by krusynth** [18F/open-source-guide#8]
I was hoping you all might be open to discussing a few slightly more prescriptive guidelines for naming conventions. There are two areas in particular that I think are problematic in our industry with regard to naming, which makes projects especially hard to find (especially if you're looking for docs or support) : 

1) Avoid "clever" naming. The world has a lot of projects with puns in the name or other cleverness that makes them rather hard to find. For example, the number of Javascript projects with some coffee-pun in the title is enormous. It'd be useful if developers were encouraged to avoid names that are just jokes and ambiguous. (I'll take `postgresql-node-session-connector` over `Barista` any day.)

2) Check to see that the name isn't already used. [I've brought this up before](https://github.com/18F/gitter/issues/12) but it's also really hard to find projects when they're using a name that's already used by another highly-used project. A quick google search before deciding on a name can save lots of time for your users later.

**Comment by krusynth** [comment]
That being said,

> There are only two hard things in Computer Science: cache invalidation and naming things.
> 
> -- Phil Karlton

**Comment by melodykramer** [comment]
These are both great suggestions and I am happy to add them to the naming part of the document, unless you'd like to. Let me know! Thanks for writing in! Mel

**Comment by krusynth** [comment]
Sure thing! Maybe we can iterate on the language here first, and then I can send a PR with whatever looks good to you? Maybe something like:

```
To help users find and recognize your project, we recommend using descriptive names that describe what your project does. You should avoid acronyms and clever names/puns as those can make it hard to search for projects. 

You should also do a quick search on the web for your project's name to make sure that name isn't already being used by other software or services, even if it's used in a different space, as it can be confusing for new users. It’s also important to check with your communications team before naming a project so that it can be cleared, if need be.

For example, if you were creating a template your coworkers could use to create guides, a good name for the repo might be *guides-template*. Bad names might include *the-unnamed-project-that-makes-it-easy-to-build-stuff*, *temp-latte*, or *guidestar*.
```

**Comment by melodykramer** [comment]
Looks good to me!

**Comment by melodykramer** [comment]
Added: https://github.com/18F/open-source-guide/pull/11

**Comment by krusynth** [comment]
:smile:
